/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.algorithmics.sablecc.analysis;

import com.algorithmics.sablecc.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAAndSentence(AAndSentence node);
    void caseAOrSentence(AOrSentence node);
    void caseAVarSentence(AVarSentence node);
    void caseANotvarSentence(ANotvarSentence node);
    void caseANotsentenceSentence(ANotsentenceSentence node);

    void caseTLpar(TLpar node);
    void caseTRpar(TRpar node);
    void caseTBlank(TBlank node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTNot(TNot node);
    void caseTVar(TVar node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
